### ISSUE TITLE
Don't forget delete "debuggable = true" before generated signed App

### ISSUE THREAD

**Issue by igorm705** [Mindinventory/Google-Play-Asset-Delivery-Sample#1]
Remove "debuggable = true" from app/build.gradle if you upload your signed app to Play Console of Google.  If you don't do it you will get error "This app is not sighed"

**Comment by akashmi** [comment]
https://github.com/Mindinventory/Google-Play-Asset-Delivery-Sample/commit/a786d30de04f4ce0b71f104c0f6660fae108e728
